title: Ye0ni
logo: /assets/img/logo.jpg
email: iju.yeon0316@gmail.com
description: ë†°ê°€ í•´ì•¼ í•˜ëŠ” ì¼
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Ye0ni
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  - name: HOMEğŸ 
    link: /index.html
    sublist:
      - name: Image
        link: .index.html#small-image
  - name: HTML
    link: /HTML1.html
  - name: CertificateğŸªª
    link: /another-page.html
